spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "*"            
            allowedMethods:
              - GET
              - POST
      httpclient:
        wiretap: true
        connect-timeout: 30000
        response-timeout: 30s
      httpserver:
        wiretap: true
      routes:
        - id: mysc_v2
          uri: http://localhost:9998/
          predicates:
            - Path=/mysc_v2/**
          filters:
            - CustomAuthFilter
            - name: Hystrix
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack
        - id: mysc-api-instance
          uri: http://msc-dev.voicecaddie.co.kr/
          predicates:
            - Path=/mysc/**
          filters:
            - CustomAuthFilter
            - name: RequestSize
              args: 
                maxSize : 10000000
            - name: Hystrix
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack
        - id: vse_app
          uri: http://13.124.120.152:8710/
          predicates:
            - Path=/vse_app/**
          filters:            
            - CustomNewAuthFilter
            - name: RequestSize
              args: 
                maxSize : 7000000
            - name: Hystrix
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack
        - id: y1
          uri: https://fapi.voicecaddie.co.kr:8810/
          predicates:
            - Path=/y1/**
          filters:            
            - CustomAuthFilter
            - name: Hystrix
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack
        - id: demo
          uri: lb://demo
          predicates:
            - Path=/demo/**
          filters:
            - CustomAuthFilter
            - name: Hystrix
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack
        - id: vc-msc
          uri: http://52.78.124.57:8750/
          predicates:
            - Path=/msc/**
          filters:
            - CustomAuthFilter
            - name: CircuitBreaker
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack
        - id: mvc-app
          uri: http://52.79.174.140:8101/
          predicates:
            - Path=/mvc_app/**
          filters:
            - CustomAuthFilter
            - name: RequestSize
              args: 
                maxSize : 10000000
            - name: Hystrix
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack       
                
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://admin:admin@172.31.5.58:8761/eureka/
  instance:
    hostname: localhost
