spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allow-credentials: true  
            allowedMethods:
              - GET
              - POST              
        httpclient:
          connect-timeout: 10000
          response-timeout: 50s
          wiretap: true
        httpserver:
          wiretap: true
      routes:
        - id: vcAppApi
          uri: lb://vcAppApi
          predicates:
            - Path=/api/**
          filters:
            - CustomAuthFilter
            - name: CircuitBreaker
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://admin:admin@localhost:8761/eureka/
  instance:
    hostname: localhost
