spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
      httpclient:
        wiretap: true
        connect-timeout: 1000
        response-timeout: 5s
      httpserver:
        wiretap: true
      routes:
        - id: msc-v2
          uri: http://127.0.0.1:9998/
          predicates:
            - Path=/mysc_v2/**
          filters:
            - CustomAuthFilter
            - name: CircuitBreaker
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack
                
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://admin:admin@localhost:8761/eureka/
  instance:
    hostname: localhost
