spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allow-credentials: true  
            allowedMethods:
              - GET
              - POST              
        httpclient:
          connect-timeout: 10000
          response-timeout: 50s
          wiretap: true
        httpserver:
          wiretap: true
      routes:
        - id: mysc-api-instance
          uri: http://localhost:9998
          predicates:
            - Path=/mysc/**
          filters:
            - CustomAuthFilter
            - name: RequestSize
              args:
                maxSize: 50000000
            - name: Hystrix
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack
        - id: mysc2-api
          uri: http://localhost:9998
          predicates:
            - Path=/v2_mysc/**
          filters:
            - CustomAuthFilter
            - name: RequestSize
              args:
                maxSize: 50000000
            - name: Hystrix
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://admin:admin@localhost:8761/eureka/
  instance:
    hostname: localhost
